package com.project.view.gui;
import com.project.controller.OracleService;
import com.project.controller.PostgresqlService;
import com.project.dto.EstudianteDTO;

import javax.swing.SpinnerNumberModel;

public class MenuEstudiantes extends javax.swing.JPanel {

    /**
     * Creates new form MenuEstudiantes
     */
    public MenuEstudiantes(String conectadoA) {
        initComponents();
        conectado_a.setText(conectadoA);
        configurarSpinner();

    }

    public void configurarSpinner() {
        SpinnerNumberModel nm = new SpinnerNumberModel();
        nm.setMinimum(1);
        campo_codigo.setModel(nm);
        campo_codigo.setValue(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo_connect_oracle1 = new javax.swing.JLabel();
        conectado_a = new javax.swing.JLabel();
        label_instruccion = new javax.swing.JLabel();
        boton_cargar = new javax.swing.JButton();
        foto_estudiante = new javax.swing.JLabel();
        segundoApellido = new javax.swing.JLabel();
        primerApellido = new javax.swing.JLabel();
        label_codigo = new javax.swing.JLabel();
        label_telefono = new javax.swing.JLabel();
        label_inicio = new javax.swing.JLabel();
        label_facultad = new javax.swing.JLabel();
        label_programa = new javax.swing.JLabel();
        nombres = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();
        programa = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        fecha_inicio = new javax.swing.JLabel();
        facultad = new javax.swing.JLabel();
        campo_codigo = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(730, 610));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_connect_oracle1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        titulo_connect_oracle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_connect_oracle1.setText("CONECTADO A  ---> ");
        add(titulo_connect_oracle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 16, 393, -1));

        conectado_a.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        conectado_a.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conectado_a.setText("DB");
        add(conectado_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 230, -1));

        label_instruccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_instruccion.setText("Selecciona el Estudiante para visualizar los datos");
        add(label_instruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        boton_cargar.setText("CARGAR");
        boton_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cargarActionPerformed(evt);
            }
        });
        add(boton_cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        foto_estudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/view/gui/images/user.jpeg"))); // NOI18N
        add(foto_estudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 210, 190));

        segundoApellido.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        segundoApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(segundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 200, -1));

        primerApellido.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        primerApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(primerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 200, -1));

        label_codigo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        label_codigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_codigo.setText("CÓDIGO:");
        add(label_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 130, -1));

        label_telefono.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        label_telefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_telefono.setText("TELÉFONO");
        add(label_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 130, -1));

        label_inicio.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        label_inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_inicio.setText("FECHA INICIO");
        add(label_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 160, -1));

        label_facultad.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        label_facultad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_facultad.setText("FACULTAD");
        add(label_facultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 130, -1));

        label_programa.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        label_programa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_programa.setText("PROGRAMA");
        add(label_programa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 130, -1));

        nombres.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        nombres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 130, -1));

        codigo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        codigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 130, -1));

        programa.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        programa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(programa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 130, -1));

        telefono.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        telefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 130, -1));

        fecha_inicio.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        fecha_inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(fecha_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 130, -1));

        facultad.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        facultad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(facultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 130, -1));
        add(campo_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 120, -1));

        jButton1.setText("CAMBIAR FOTO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void boton_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cargarActionPerformed

        if ("Oracle".equals(conectado_a.getText())) {
            EstudianteDTO est = OracleService.getInstance().buscarIdEstudianteOracle((Number) campo_codigo.getValue());
            
            codigo.setText(est.getCodigo().toString());
            nombres.setText(est.getNombres().toUpperCase());
            primerApellido.setText(est.getApellido1().toUpperCase());
            segundoApellido.setText(est.getApellido2().toUpperCase());
            telefono.setText(est.getTelefono());
            facultad.setText(est.getFacultad());
            programa.setText(est.getPrograma());
            fecha_inicio.setText(est.getFecha_inicio().toString());
            //foto.setText(est.getFecha_inicio());
            
        } else if("PostgreSQL".equals(conectado_a.getText())){
            
        }
    }//GEN-LAST:event_boton_cargarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_cargar;
    private javax.swing.JSpinner campo_codigo;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel conectado_a;
    private javax.swing.JLabel facultad;
    private javax.swing.JLabel fecha_inicio;
    private javax.swing.JLabel foto_estudiante;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel label_codigo;
    private javax.swing.JLabel label_facultad;
    private javax.swing.JLabel label_inicio;
    private javax.swing.JLabel label_instruccion;
    private javax.swing.JLabel label_programa;
    private javax.swing.JLabel label_telefono;
    private javax.swing.JLabel nombres;
    private javax.swing.JLabel primerApellido;
    private javax.swing.JLabel programa;
    private javax.swing.JLabel segundoApellido;
    private javax.swing.JLabel telefono;
    private javax.swing.JLabel titulo_connect_oracle1;
    // End of variables declaration//GEN-END:variables
}
