package com.project.view.gui;

public class MenuEstudiantes extends javax.swing.JPanel {

    /**
     * Creates new form MenuEstudiantes
     */
    public MenuEstudiantes(String conectadoA) {
        initComponents();
        conectado_a.setText(conectadoA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo_connect_oracle1 = new javax.swing.JLabel();
        conectado_a = new javax.swing.JLabel();
        label_instruccion = new javax.swing.JLabel();
        boton_cargar = new javax.swing.JButton();
        foto_estudiante = new javax.swing.JLabel();
        conectado_a1 = new javax.swing.JLabel();
        apellidos = new javax.swing.JLabel();
        label_codigo = new javax.swing.JLabel();
        label_telefono = new javax.swing.JLabel();
        label_inicio = new javax.swing.JLabel();
        label_facultad = new javax.swing.JLabel();
        label_programa = new javax.swing.JLabel();
        nombres = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();
        programa = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        fecha_inicio = new javax.swing.JLabel();
        facultad = new javax.swing.JLabel();
        campo_id = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(730, 610));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_connect_oracle1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        titulo_connect_oracle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_connect_oracle1.setText("CONECTADO A  ---> ");
        add(titulo_connect_oracle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 16, 393, -1));

        conectado_a.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        conectado_a.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conectado_a.setText("DB");
        add(conectado_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 230, -1));

        label_instruccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_instruccion.setText("Selecciona el Estudiante para visualizar los datos");
        add(label_instruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        boton_cargar.setText("CARGAR");
        add(boton_cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        foto_estudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/view/gui/images/user.jpeg"))); // NOI18N
        add(foto_estudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 210, 190));

        conectado_a1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        conectado_a1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conectado_a1.setText("SEGUNDO APELLIDO");
        add(conectado_a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 200, -1));

        apellidos.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        apellidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apellidos.setText("PRIMER APELLIDO");
        add(apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 200, -1));

        label_codigo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        label_codigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_codigo.setText("CÓDIGO:");
        add(label_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 130, -1));

        label_telefono.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        label_telefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_telefono.setText("TELÉFONO");
        add(label_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 130, -1));

        label_inicio.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        label_inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_inicio.setText("FECHA INICIO");
        add(label_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 160, -1));

        label_facultad.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        label_facultad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_facultad.setText("FACULTAD");
        add(label_facultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 130, -1));

        label_programa.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        label_programa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_programa.setText("PROGRAMA");
        add(label_programa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 130, -1));

        nombres.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        nombres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombres.setText("NOMBRES");
        add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 130, -1));

        codigo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        codigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigo.setText("CÓDIGO");
        add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 130, -1));

        programa.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        programa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        programa.setText("label_programa");
        add(programa, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 130, -1));

        telefono.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        telefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telefono.setText("label_telefono");
        add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 130, -1));

        fecha_inicio.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        fecha_inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha_inicio.setText("label_inicio");
        add(fecha_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 130, -1));

        facultad.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        facultad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        facultad.setText("label_facultad");
        add(facultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 130, -1));

        campo_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_idActionPerformed(evt);
            }
        });
        add(campo_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void campo_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_idActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidos;
    private javax.swing.JButton boton_cargar;
    private javax.swing.JTextField campo_id;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel conectado_a;
    private javax.swing.JLabel conectado_a1;
    private javax.swing.JLabel facultad;
    private javax.swing.JLabel fecha_inicio;
    private javax.swing.JLabel foto_estudiante;
    private javax.swing.JLabel label_codigo;
    private javax.swing.JLabel label_facultad;
    private javax.swing.JLabel label_inicio;
    private javax.swing.JLabel label_instruccion;
    private javax.swing.JLabel label_programa;
    private javax.swing.JLabel label_telefono;
    private javax.swing.JLabel nombres;
    private javax.swing.JLabel programa;
    private javax.swing.JLabel telefono;
    private javax.swing.JLabel titulo_connect_oracle1;
    // End of variables declaration//GEN-END:variables
}
